import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import path, { dirname } from "node:path";

import { decompressTarZst, parseTar, resolveZigZstdExe } from "./win-tar";

// electrobun's Windows "Setup" exe is a self-extracting extractor with console
// output — no wizard, no uninstaller. This hook compiles a standard Inno Setup
// wizard installer so [Files] installs the real app bundle — the tar/extractor
// path never enters the picture. The wizard installer is the primary Windows
// deliverable; electrobun's exe/zip/tar stay as side artifacts. Local-only:
// requires Inno Setup 6 on the machine (`winget install JRSoftware.InnoSetup`);
// not part of CI. Runs in postPackage, after electrobun created its own Setup
// exe / zip / artifacts.
//
// At postPackage the app bundle folder is gone: electrobun deletes it after
// tarring (src/cli/index.ts — `rmSync(appBundleFolderPath, ...)` when
// buildEnvironment !== "dev") and replaces it with the self-extracting wrapper
// (extractor stub + Resources/<hash>.tar.zst). The only complete copy of the
// bundle left is the channel's tar.zst, so this hook decompresses it and
// extracts the bundle into a dot-prefixed staging dir (never scanned by
// `*-win-x64` walks or the icon-embed hook), then compiles ISCC from there.
// Channels without a tar.zst (e.g. dev) are skipped.
if (process.platform !== "win32") process.exit(0);

const desktopRoot = path.resolve(import.meta.dir, "..");
const buildDir = path.join(desktopRoot, "build");
const { version } = JSON.parse(
  readFileSync(path.join(desktopRoot, "package.json"), "utf8")
) as { version: string };

const iscc = [
  ...(process.env.PATH ?? "").split(";").filter(Boolean).map((dir) => path.join(dir, "ISCC.exe")),
  path.join(
    process.env["ProgramFiles(x86)"] ?? "C:\\Program Files (x86)",
    "Inno Setup 6",
    "ISCC.exe"
  ),
].find((candidate) => existsSync(candidate));
if (!iscc) {
  console.error(
    "[build-wizard-installer] ISCC.exe not found — install Inno Setup 6 first: winget install JRSoftware.InnoSetup"
  );
  process.exit(1);
}

const iconIco = path.join(buildDir, "temp-app-icon.ico");

for (const channelDir of readdirSync(buildDir)) {
  if (!channelDir.endsWith("-win-x64")) continue;
  const channelPath = path.join(buildDir, channelDir);

  const tarZst = readdirSync(channelPath)
    .filter((name) => name.endsWith(".tar.zst") && name !== "prev.tar.zst")
    .sort()[0];
  if (!tarZst) {
    console.warn(`[build-wizard-installer] no .tar.zst in ${channelPath}, skipping`);
    continue;
  }
  const channel = channelDir.replace("-win-x64", "");
  const issPath = path.join(channelPath, `installer-${channel}.iss`);

  const zigZstd = resolveZigZstdExe();
  const tarPath = path.join(channelPath, `.wizard-${tarZst}.tar`); // temporary decompressed tar
  const stagingDir = path.join(channelPath, ".wizard-app-bundle"); // ISCC compile source
  decompressTarZst(zigZstd, path.join(channelPath, tarZst), tarPath);
  const entries = parseTar(readFileSync(tarPath));
  if (existsSync(stagingDir)) rmSync(stagingDir, { recursive: true, force: true });
  mkdirSync(stagingDir, { recursive: true });
  for (const entry of entries) {
    // electrobun's tar is rooted at the bundle folder (e.g. LLMSpace-canary/);
    // strip that leading component so staging holds the bundle contents
    // directly and `Source: "<stagingDir>\*"` installs {app}\bin\launcher.exe.
    const slash = entry.name.indexOf("/");
    const rel = slash === -1 ? entry.name : entry.name.slice(slash + 1);
    if (!rel) continue;
    const dest = path.join(stagingDir, rel);
    if (entry.type === "5") {
      mkdirSync(dest, { recursive: true });
    } else if (entry.type === "0") {
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, entry.data);
    }
  }
  console.info(
    `[build-wizard-installer] extracted ${entries.length} entries from ${tarZst} to ${stagingDir}`
  );

  // String.raw keeps backslashes literal — a plain template literal would
  // turn `\b`/`\t`/`\*` into escapes and corrupt the .iss.
  const iss = String.raw`; Generated by build-wizard-installer.ts — do not edit by hand.
#define MyAppName "LLM Space"
#define MyAppVersion "${version}"
#define MyAppChannel "${channel}"
#define MyAppExeName "bin\launcher.exe"

[Setup]
AppId=tech.deerflow.llm-space.${channel}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher=deer-flow
DefaultDirName={localappdata}\tech.deerflow.llm-space\{#MyAppChannel}\app
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
OutputBaseFilename=LLMSpace-Setup-{#MyAppChannel}
SetupIconFile=${iconIco}
UninstallDisplayIcon={app}\{#MyAppExeName}
WizardStyle=modern
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Files]
Source: "${stagingDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent
`;
  writeFileSync(issPath, iss);

  try {
    console.info(`[build-wizard-installer] compiling ${issPath} (ISCC: ${iscc})`);
    execFileSync(iscc, ["/Qp", `/O${channelPath}`, issPath]);

    const setupExeName = `LLMSpace-Setup-${channel}.exe`;
    const setupExePath = path.join(channelPath, setupExeName);
    console.info(`[build-wizard-installer] wrote ${setupExePath}`);

    const prefix = [
      Bun.env.ELECTROBUN_BUILD_ENV,
      Bun.env.ELECTROBUN_OS,
      Bun.env.ELECTROBUN_ARCH,
    ]
      .filter(Boolean)
      .join("-");
    const artifactDir = Bun.env.ELECTROBUN_ARTIFACT_DIR;
    if (artifactDir && prefix) {
      const dest = path.join(artifactDir, `${prefix}-${setupExeName}`);
      copyFileSync(setupExePath, dest);
      console.info(`[build-wizard-installer] artifact ${dest}`);
    }
  } finally {
    // Never leave half-built staging or a temp tar behind — clean up on both
    // success and compile failure (ISCC throwing exits non-zero).
    rmSync(stagingDir, { recursive: true, force: true });
    rmSync(tarPath, { force: true });
  }
}
