import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

// electrobun's Windows "Setup" exe is a self-extracting extractor with console
// output — no wizard, no uninstaller. This hook compiles a standard Inno Setup
// wizard installer straight from the already-built (icon-embedded) bundle at
// build/<channel>-win-x64/LLMSpace-<channel>/, so [Files] installs the real
// directory — the tar/extractor path never enters the picture. The wizard
// installer is the primary Windows deliverable; electrobun's exe/zip/tar stay
// as side artifacts. Local-only: requires Inno Setup 6 on the machine
// (`winget install JRSoftware.InnoSetup`); not part of CI. Runs in postPackage,
// after electrobun created its own Setup exe / zip / artifacts.
if (process.platform !== "win32") process.exit(0);

const desktopRoot = path.resolve(import.meta.dir, "..");
const buildDir = path.join(desktopRoot, "build");
const { version } = JSON.parse(
  readFileSync(path.join(desktopRoot, "package.json"), "utf8")
) as { version: string };

const iscc = [
  ...(process.env.PATH ?? "").split(";").filter(Boolean).map((dir) => path.join(dir, "ISCC.exe")),
  path.join(
    process.env["ProgramFiles(x86)"] ?? "C:\\Program Files (x86)",
    "Inno Setup 6",
    "ISCC.exe"
  ),
].find((candidate) => existsSync(candidate));
if (!iscc) {
  console.error(
    "[build-wizard-installer] ISCC.exe not found — install Inno Setup 6 first: winget install JRSoftware.InnoSetup"
  );
  process.exit(1);
}

const iconIco = path.join(buildDir, "temp-app-icon.ico");

for (const channelDir of readdirSync(buildDir)) {
  if (!channelDir.endsWith("-win-x64")) continue;
  const channelPath = path.join(buildDir, channelDir);

  const bundle = readdirSync(channelPath, { withFileTypes: true }).find(
    (entry) => entry.isDirectory() && entry.name.startsWith("LLMSpace-")
  );
  if (!bundle) {
    console.warn(`[build-wizard-installer] no LLMSpace-* bundle in ${channelPath}, skipping`);
    continue;
  }
  const channel = bundle.name.replace("LLMSpace-", "");
  const bundlePath = path.join(channelPath, bundle.name);
  const issPath = path.join(channelPath, `installer-${channel}.iss`);

  // String.raw keeps backslashes literal — a plain template literal would
  // turn `\b`/`\t`/`\*` into escapes and corrupt the .iss.
  const iss = String.raw`; Generated by build-wizard-installer.ts — do not edit by hand.
#define MyAppName "LLM Space"
#define MyAppVersion "${version}"
#define MyAppChannel "${channel}"
#define MyAppExeName "bin\launcher.exe"

[Setup]
AppId=tech.deerflow.llm-space.${channel}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher=deer-flow
DefaultDirName={localappdata}\tech.deerflow.llm-space\{#MyAppChannel}\app
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
OutputBaseFilename=LLMSpace-Setup-{#MyAppChannel}
SetupIconFile=${iconIco}
UninstallDisplayIcon={app}\{#MyAppExeName}
WizardStyle=modern
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Files]
Source: "${bundlePath}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent
`;
  writeFileSync(issPath, iss);

  console.info(`[build-wizard-installer] compiling ${issPath} (ISCC: ${iscc})`);
  execFileSync(iscc, ["/Qp", `/O${channelPath}`, issPath]);

  const setupExeName = `LLMSpace-Setup-${channel}.exe`;
  const setupExePath = path.join(channelPath, setupExeName);
  console.info(`[build-wizard-installer] wrote ${setupExePath}`);

  const prefix = [
    Bun.env.ELECTROBUN_BUILD_ENV,
    Bun.env.ELECTROBUN_OS,
    Bun.env.ELECTROBUN_ARCH,
  ]
    .filter(Boolean)
    .join("-");
  const artifactDir = Bun.env.ELECTROBUN_ARTIFACT_DIR;
  if (artifactDir && prefix) {
    const dest = path.join(artifactDir, `${prefix}-${setupExeName}`);
    copyFileSync(setupExePath, dest);
    console.info(`[build-wizard-installer] artifact ${dest}`);
  }
}
